tasks:
  sync-locks:
    triggers:
    - "pixi.toml"
    - "pixi.lock"
    stage:
    - "pixi.lock"
    - "envs/"

  generate-config:
    triggers:
    - "scripts/lib/validation/config/**"
    stage:
    - "config/"
    - "doc/"
    - "*.yaml"
    - "*.yml"

app:
  runs:
    - name: "myopic test"
      configfile: "config/test/config.myopic.yaml"
      triggers: [main, pr]
      cache:
        key: "myopic-test-{YYYY}-{MM}"
        dirs: ["data"]
